### ISSUE TITLE
Navigation behaving not quite as expected

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_blacklight#1376]
We had a question from a librarian about why our page navigation looks like:

<img width="332" alt="Image" src="https://github.com/user-attachments/assets/4fd17bd2-b09c-4dcd-a8d8-2ae836f1c1d3" />

## Pagination

Agreed this is not intuitive and the ... feels like it should be clickable.

Ideally, the final page would be on the end of the list as a "jump to last."  Similarly, the 1 would remain up front. We could retain the ... as a helpful separator.

So:

1 2 3 4 5 ... 128

or 1 ... 7 8 9 10 11 ... 128

## Previous / Next Navigation

Similarly, we the Previous/Next navigation is on the left side. How hard is it to split to put each on the side of the "direction" you'd expect to move? This isn't as important as pagination but would be nice to have.

**Comment by granta03** [comment]
@ruthtillman I have fixed the logic for the pagination as well as moved the next navigation button to the right side. I do have one question. This is how the current pagination bar looks like with my changes in the case of where the current page is close enough to the middle where both ends can show ellipses. Would you the length of the window of what page numbers show to be smaller than it currently is or is the current window good as is?

<img width="808" alt="Image" src="https://github.com/user-attachments/assets/c227495a-d61e-4f78-91d7-4d1b91d9a474" />

**Comment by granta03** [comment]
<img width="804" alt="Image" src="https://github.com/user-attachments/assets/0e73a494-49ef-4131-9196-58c5a3db2e0e" />

<img width="759" alt="Image" src="https://github.com/user-attachments/assets/2bddfd12-762a-4090-b5a9-c3296a88c55a" />

<img width="749" alt="Image" src="https://github.com/user-attachments/assets/bbfc1dc0-5fa3-43fe-b771-564d9b00693a" />

<img width="767" alt="Image" src="https://github.com/user-attachments/assets/fa513eb1-173d-46b1-b003-1f5769b0a812" />

here are some other examples of what the pagination bar looks like in other cases

**Comment by ruthtillman** [comment]
1. Big picture, the overall behavior is great!
2. Re: the length of the bar/number of page numbers shown, I think it would be good to cut back a little. I don't know how the logic is set up. If it's consistent throughout, then what if we trimmed just one off? So the center bar would be: 4, 5, 6, 7, 8, 9, 10 around the 7? That way we'd still get 4 digits if it's on either end of the pagination. If the setting for when it's in the middle is separate, then maybe we could cut two off each end, so it would be 5, 6, 7, 8, 9 around the 7.

> [@ruthtillman](https://github.com/ruthtillman) I have fixed the logic for the pagination as well as moved the next navigation button to the right side. I do have one question. This is how the current pagination bar looks like with my changes in the case of where the current page is close enough to the middle where both ends can show ellipses. Would you the length of the window of what page numbers show to be smaller than it currently is or is the current window good as is?
> <img alt="Image" width="808" src="https://private-user-images.githubusercontent.com/129565055/418176884-c227495a-d61e-4f78-91d7-4d1b91d9a474.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEwMjE3ODEsIm5iZiI6MTc0MTAyMTQ4MSwicGF0aCI6Ii8xMjk1NjUwNTUvNDE4MTc2ODg0LWMyMjc0OTVhLWQ2MWUtNGY3OC05MWQ3LTRkMWI5MWQ5YTQ3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwM1QxNzA0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzFmYzNhYTZlYTJkYzg2OWU1N2I4MTc3YzY5ZjlhMmIxZjYxYTM3NmEwN2U3YTc1YWMyYmI3YjY3NGIxODY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ko_45yFH7MXrIQ-fBYbF8NyskQR2Y7iaxzA8Fn1N40w">

**Comment by granta03** [comment]
Here is how it looks with window size 3:
<img width="780" alt="Image" src="https://github.com/user-attachments/assets/6660f694-216a-4862-aed8-18e57e70f992" />
<img width="770" alt="Image" src="https://github.com/user-attachments/assets/d886086d-ab51-4b6c-96e5-b6a6a7a91d97" />
<img width="757" alt="Image" src="https://github.com/user-attachments/assets/c8bd0cc9-3846-466d-b4c9-3b249c38518f" />
<img width="770" alt="Image" src="https://github.com/user-attachments/assets/dc0c7481-3b3d-4b67-b40f-e985aca4f988" />

**Comment by ruthtillman** [comment]
I think window size 3 looks good! Enough to give some context but realistically most people will hit next or first/last ones.
